### PR TITLE
Do not pass empty schema into the request

### PR DESCRIPTION
**Pull request by gvidon**
Goodtables validation will always return true when empty schema param is passed to request.

### CODE REVIEW

**Comment by pwalsh** [comment]
How does this translate into the actual query? Because the API itself can take an "empty" schema, which means no schema. eg: 

http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fraw.githubusercontent.com%2Fokfn%2Fgoodtables-web%2Fmaster%2Fexamples%2Finvalid-on-structure.csv&format=csv&encoding=&schema_url=

Or maybe you actually mean `{}` as the schema object, in which case you are right I guess.

**Comment by gvidon** [comment]
It says that empty object is not a valid schema http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fraw.githubusercontent.com%2Fokfn%2Fgoodtables-web%2Fmaster%2Fexamples%2Finvalid-on-structure.csv&format=csv&encoding=&schema_url=&schema=%7B%7D and then reports that there are 0 errors in data.

**Comment by pwalsh** [comment]
@gvidon right. So, fix this here, and open an issue on https://github.com/okfn/goodtables/issues

**Comment by pwalsh** [comment]
is the failing test just timeouts on travis?

**Comment by gvidon** [comment]
@pwalsh this repo is just not configured for travis. I can fix that today.
https://travis-ci.org/okfn/goodtables-js

**Comment by gvidon** [comment]
Created issue https://github.com/okfn/goodtables/issues/60

**Pull request merged**
