### PR TITLE
Expose detected encoding from server

### PR DESCRIPTION
**Pull request by akariv**

### CODE REVIEW

**Comment by akariv** [comment]
@pwalsh

**Comment by pwalsh** [comment]
All good.

**Comment by pwalsh** [comment]
@akariv pls create a user on npm so i can make you an owner on this package, and you can bump version and publish

**Comment by akariv** [comment]
@pwalsh updated the PR

**Comment by pwalsh** [comment]
ready to merge.

**Comment by akariv** [comment]
Not the best day to register a new user with npm, but still - it's 'akariv'

**Comment by pwalsh** [comment]
@akariv added you on npm so you can merge and then bump version to publish.

**Pull request merged**
